#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

bindkey -M vicmd '/' history-incremental-search-backward
bindkey -M vicmd '?' history-incremental-search-forward

# Push the current buffer onto the buffer stack and clear the buffer. 
# Next time the editor starts up, the buffer will be popped off the top of
# the buffer stack and loaded into the editing buffer.
bindkey -M vicmd "q" push-line-or-edit

bindkey ' ' magic-space

# Default hook for local zshrc file
zshrcFiles=("${HOME}/.zshrc.local")

# Hook for OS specific file
OS=`uname`
if [ "${OS}" = "Darwin" ]; then
  OS=mac
fi
zshrcFiles+=("${HOME}/.zshrc.${OS}")

# Sourcing hook files if available
for zf in $zshrcFiles; do
  if [[ -f $zf ]]; then
    source $zf
  fi
done
